plugins {
	id 'java-library'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.141'
	id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
	distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
	archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
	main {
		java {
			srcDirs = ['src/main/java']
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}
	client {
		java {
			srcDirs = ['src/client/java']
		}
		resources {
			srcDirs = ['src/client/resources']
		}
	}
}

configurations {
	clientImplementation.extendsFrom implementation
	clientCompileClasspath.extendsFrom compileClasspath
	clientRuntimeClasspath.extendsFrom runtimeClasspath
}

dependencies {
	clientImplementation sourceSets.main.output
}

sourceSets.main.resources {
	srcDir('src/generated/resources')
	exclude("**/*.bbmodel")
}

repositories {
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

neoForge {
	version = project.neo_version

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {
		client {
			client()
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}
		server {
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}
		data {
			data()
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}
		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 21
}

java {
	withSourcesJar()
}

jar {
	dependsOn(clientClasses)
	from("LICENSE") {
		rename { "${it}_${project.mod_id}" }
	}
	from(sourceSets.client.output)
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
	var replaceProperties = [
		minecraft_version          : minecraft_version,
		minecraft_version_range    : minecraft_version_range,
		neo_version                : neo_version,
		loader_version_range       : loader_version_range,
		mod_id                     : mod_id,
		mod_name                   : mod_name,
		mod_license                : mod_license,
		mod_version                : mod_version,
		mod_group_id               : mod_group_id,
	]
	inputs.properties replaceProperties
	expand replaceProperties
	from "src/main/templates"
	into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
	publications {
		register('mavenJava', MavenPublication) {
			from components.java
		}
	}
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}
