org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.10.7-hotspot
org.gradle.daemon=false

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
neoforge_version=21.11.42
neoforge_version_range=[21.11,)
loader_version_range=[1,)
mapping_channel=official
mapping_version=1.21.11

mod_id=trmt
mod_name=The Roads More Travelled
mod_license=CC-BY-NC-4.0
mod_version=0.5.1-1.21.11-neoforge
mod_group_id=milkucha.trmt
mod_authors=milkucha
mod_description=An erosion mod for Minecraft
